services:
  planet-search:
    build: .
    network_mode: host
    volumes:
      - ./pbf:/app/data/sources
      - ./src/test/resources/extenal.geojson:/external/external.geojson
      - ./output:/output
    environment:
      - JAVA_OPTS=-Xmx2g -Xms2g
    command:
      - --es-address=http://localhost:9200
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
