name: Build and publish docker image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: build and run tests
        run: |
          mvn clean install
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
      - name: End to End tests setup
        run: |
          docker compose up -d elasticsearch
          docker compose up planet-search 
      - name: End to End tests  
        run: |-
          curl -s -X GET http://localhost:9200/points/_search?pretty -H 'Content-Type: application/json'

