name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: End to End tests setup
        run: |
          docker compose up -d elasticsearch
          docker compose build planet-search
      - name: End to End tests using curl
        run: |-
          mkdir -p ./data/input
          cp ./src/test/resources/extenal.geojson ./data/input/external.geojson
          docker compose up planet-search 
          curl -s -X GET http://localhost:9200/points/_search?pretty -H 'Content-Type: application/json'
      - name: Check that a PMTiles was created
        if: ${{ hashFiles('./data/output/global_points.pmtilesss') == '' }}
        run: echo "File was not created" && exit 1

  Java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 23
      - name: End to End tests setup
        run: |
          docker compose up -d elasticsearch
      - name: Build
        run: mvn clean install -DskipTests
      - name: End to End test using Java
        run: mvn test -Prun-all-tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

