name: Build and publish docker image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: End to End tests setup
        run: |
          docker compose up -d elasticsearch
          docker compose up planet-search 
      - name: End to End tests  
        run: |-
          curl -s -X GET http://localhost:9200/points/_search?pretty -H 'Content-Type: application/json'

